feat: support multi-argument locks
When pasting from a pull request or migration, it's useful to do:

```shell
pglx explain SHARE UPDATE EXCLUSIVE
```

However, this currently fails with an error message:

```shell
error: unexpected argument 'UPDATE' found

Usage: pglx explain <LOCK>

For more information, try '--help'.
```

This is because we're passing 3 arguments (`SHARE`, `UPDATE` and
`EXCLUSIVE`) instead of a singular argument (`SHARE UPDATE EXCLUSIVE`)
which `clap` obviously doesn't like. Since it doesn't entirely support
this kind of behaviour, we can just take the "free arguments" and
concatenate them ourselves.

`clap` was just using our own `from_str` method anyway, so this doesn't
really change the error outputs when you supply an invalid lock.

This change:
* Swaps from `Lock` to `Vec<String>` and parses the lock type in the
  handler instead